#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define DEXTER_VERSION "0.0.0"
#define DEXTER_TOTAL_INTERUPTS 512
#define DEXTER_TOTAL_GDT_SEGMENTS 6

// 100 MB heap size
#define DEXTER_HEAP_SIZE_BYTES 104857600
#define DEXTER_HEAP_BLOCK_SIZE 4096
#define DEXTER_HEAP_ADDRESS 0x01000000
#define DEXTER_HEAP_TABLE_ADDRESS 0x00007E00

#define DEXTER_SECTOR_SIZE 512
#define DEXTER_MAX_PATH 108
#define DEXTER_MAX_FILESYSTEMS 12
#define DEXTER_MAX_FILE_DESCRIPTORS 512

#define DEXTER_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define DEXTER_USER_PROGRAM_STACK_SIZE 1024 * 16
#define DEXTER_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define DEXTER_PROGRAM_VIRTUAL_STACK_ADDRESS_END DEXTER_PROGRAM_VIRTUAL_STACK_ADDRESS_START - DEXTER_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif